version: '3.4'

services:
  net-core-asp-api:
    image: ${DOCKER_REGISTRY-}netcoreaspapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - app-network
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: NET-Core-ASP-API/Dockerfile
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - app-network
    ports:
      - "5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  app-network:
